# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'MBTA' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MBTA
	pod 'JGProgressHUD'
	pod 'Alamofire'
  pod 'AlamofireSwiftyJSON'
	pod 'SideMenuSwift'
	pod 'SDWebImage', '~> 5.0'
	pod 'iOSDropDown'
end
